steps:
# This step runs the unit tests on the app
- name: 'maven'
  id: Test
  args:
  - 'mvn'
  - 'test'

# # This step build the app
- name: 'maven'
  id: Build
  args:
  - 'mvn'
  - 'clean'
  - 'install' 
  - '-DskipTest'

- name: 'node'
  id: testNode
  dir: './nodeApi/src'
  args:
  - 'npm'
  - 'test'

- name: 'node'
  id: buildNode
  dir: './nodeApi/src'
  args:
  - 'npm'
  - 'install'
  
# Build the container image
- name: "gcr.io/cloud-builders/docker"
  id: Login
  args:
  - "login"
  - "--username"
  - "${_USERNAME}"
  - "--password"
  - "${_PASSWORD}"

- name: "gcr.io/cloud-builders/docker"
  id: docker-build-java
  args:
  - "build"
  - "-t"
  - "${_USERNAME}/java:1"
  - "."

- name: "gcr.io/cloud-builders/docker"
  id: docker-push-java
  args:
  - "push"
  - "docker.io/${_USERNAME}/java:1"

- name: 'node'
  dir: './nodeApi/src'
  id: docker-build-node
  args:
  - "build"
  - "-t"
  - "${_USERNAME}/node:1"
  - "."

- name: 'node'
  dir: './nodeApi/src'
  id: docker-push-node
  args:
  - "push"
  - "docker.io/${_USERNAME}/node:1"